name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npx pnpm install
      - run: npx pnpm run build
      - run: npx pnpm global add vite-gh-pages
      - run: npx vite-gh-pages
